# Generated by Django 4.0 on 2022-01-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod_movement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod_move',
            name='qty',
            field=models.IntegerField(),
        ),
    ]
