# Generated by Django 4.0 on 2021-12-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='locations',
            fields=[
                ('lid', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
