# Generated by Django 4.0 on 2022-01-11 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_alter_products_options'),
        ('location', '0002_alter_locations_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='balance',
            fields=[
                ('bid', models.IntegerField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('pid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='product.products')),
                ('warehouse', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='location.locations')),
            ],
            options={
                'ordering': ['bid'],
            },
        ),
    ]
