# Generated by Django 4.0 on 2021-12-31 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='id',
        ),
        migrations.AddField(
            model_name='products',
            name='pid',
            field=models.IntegerField(default=True, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
